---
AWSTemplateFormatVersion: 2010-09-09
Description: RDE API Pipeline Resource Stack
Resources:

  ArtifactBucket:
    Type: AWS::S3::Bucket

  #ArtifactBucketPolicy:
  #  Type: AWS::S3::BucketPolicy
  #  Properties:
  #    Bucket: !ImportValue rde:devops:resources:artifactbucket
  #    PolicyDocument:
  #      Statement: 
  #      - Action: 
  #        - s3:DeleteObject
  #        - s3:GetObject
  #        - s3:GetObjectVersion
  #        - s3:ListBucket
  #        - s3:PutObject
  #        - s3:GetBucketPolicy
  #        Effect: "Allow"
  #        Resource: !Sub "arn:aws:s3:::${ArtifactBucket}/*"  #Artifact Buckets Read/Write
  #        Principal: 
  #          AWS: !Import rde:devops:roles:pipelinerole
  
  Repository:
    Type: "AWS::ECR::Repository"
    Properties: 
      RepositoryName: rde-api-1
  #    RepositoryPolicyText:
  #      Version: "2012-10-17"
  #      Statement:
  #      - Sid: CodeBuildAccess
  #        Effect: Allow
  #        Principal:
  #          Service: "codebuild.amazonaws.com"
  #        Action:
  #          - "ecr:GetDownloadUrlForLayer"
  #          - "ecr:BatchGetImage"
  #          - "ecr:BatchCheckLayerAvailability"

Outputs:
  DockerRepository:
    Description: RDE API Container Repository  
    Value: !Ref Repository
    Export:
      Name: rde:api:docker-repository
  ArtifactBucket:
    Description: RDE API Artifact Bucket  
    Value: !Ref ArtifactBucket
    Export:
      Name: rde:api:artifactbucket1
